// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzvycgufyhgiemgrkjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4enZ5Y2d1ZnloZ2llbWdya2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTY2MDcsImV4cCI6MjA2MzEzMjYwN30.8SiQVzncavoN76etnY8cA6NqPQw6Y_Ly1nrSYV7MIhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);